spring:
  cloud:
    function:
      definition: rawEventSupplier
    stream:
      source: streamBridgeRawUserEvent
      bindings:
        rawEventSupplier-out-0:
          destination: user-raw-events
        streamBridgeRawUserEvent-out-0:
          destination: user-raw-events
      rabbit:
        bindings:
          rawEventSupplier-out-0:
            producer:
              routingKeyExpression: '''users.raw.events'''
          streamBridgeRawUserEvent-out-0:
            producer:
              routingKeyExpression: '''users.raw.events'''